### ISSUE TITLE
Unnecessary data in diff?

### ISSUE THREAD

**Issue by M-Gonzalo** [rrrlasse/eXdupe#1]
I'm testing out the latest version for linux (exdupe_1.1.0.beta5_linux_amd64), and after creating a full backup, the diff is about 5% of the uncompressed original size, even without adding or modifying anything in the dataset.

Something like:
Original: 8g
Full-zstd: 2g
Diff-uncompressed: 400m

Why is this? Is it expected behavior?

**Comment by rrrlasse** [comment]
The diff usually take up much less than 1% of the original data if it's unchanged.

What is the total file count? And what kind of data is it?

Each file is divided into 4 KB chunks and any remainder at the end is not compared. So numerous smaller files will increase the overhead.

If that's the case, you could try piping through tar. Something like (backup + restore):

tar cvf - dir1 | ./exdupe -stdin files.tar -stdout > files.full
./exdupe -R files.full -stdout | tar xf - -C dir2

Similiar for a diff backup.

**Comment by M-Gonzalo** [comment]
Oh yes that must definitely be it. It's a software directory with almost half a million tiny files, mostly node_modules

**Comment by rrrlasse** [comment]
Great. I think tar will also give a big speed increase in that use case.

**Comment by M-Gonzalo** [comment]
> Great. I think tar will also give a big speed increase in that use case.

Great, I'll test it out! exdupe is surprisingly fast, though, something like 90 secs for that amount of files, compression included.

**Comment by rrrlasse** [comment]
@M-Gonzalo maybe you want to try the new beta 6 that I've just commited. It now searches all the small file remainders also and results in a much smaller diff file.

**Comment by M-Gonzalo** [comment]
Something I noticed is that piping through tar results in a significantly smaller file (difference of ~340 MB with method 1 - zstd), at least on this particular test set. Maybe because of the sorting strategy?

**Comment by rrrlasse** [comment]
It could be because the regular compresssion with zstd can span over multiple of the small files when uing tar. Without tar it's compressing each small file individually after deduplicating them.

**Comment by M-Gonzalo** [comment]
Oh, I thought it created blocks of a fixed size to compress, like a solid-ish approach

**Comment by rrrlasse** [comment]
It now supports solid archives, so closing this issue :)
