### ISSUE TITLE
Bug report: Beta 10 linux

### ISSUE THREAD

**Issue by M-Gonzalo** [rrrlasse/eXdupe#5]
I'm testing the latest [Linux amd64](https://github.com/rrrlasse/eXdupe/raw/stuff/beta/exdupe_1.1.0.dev10_linux_amd64.tar.gz) and I believe it introduces a bug.

This is a previous version (dev8) after a few seconds:
![image](https://github.com/rrrlasse/eXdupe/assets/23223606/e523f3d1-300a-47d1-bbf1-e84eaa52d0f9)

And this is now, stuck like this for several minutes:
![image](https://github.com/rrrlasse/eXdupe/assets/23223606/2db1beb2-ff54-480a-a58f-361d2312906c)
![image](https://github.com/rrrlasse/eXdupe/assets/23223606/0f83fde7-c548-481f-a6da-5b257d1767d3)

Same command line for both.
Resulting files for both:
![image](https://github.com/rrrlasse/eXdupe/assets/23223606/a89d6ef5-7fbd-42cc-b613-f1a1516258ce)

**Comment by rrrlasse** [comment]
You're right. I'll fix it one of the next days :)

**Comment by rrrlasse** [comment]
Should be fixed now in dev11

**Comment by M-Gonzalo** [comment]
It's working, thanks!
